export interface projectDetails {
    projectheadid?: number;
    projectname?: string;
    divisionid?: number;
    subdivisionid?: number;
    rangeid?: number;
    villageid?: number;
    tahsilid?: number;
    samitteedid?: number;
    vidhansabhaid?: number;
    beatid?: number;
    compantmentid?: number;
    apoyear?: string;
    financialyear?: number;
    projecttenure?: number;
    projectarea?: string;
    schemeid?: number;
    executionsupervisor?: string;
    executionpost?: string;
    budgetheaddesc?: string;
    operationtype?: string
    project_name?: string;
    division?: string;
    subdivision?: string;
    range?: string;
    village?: string;
    tahsil?: string;
    samitee?: string;
    vidhansabha?: string;
    beat?: string;
    compartment?: string;
    site?: string;
    totalarea?: string;
    approval_year?: string;
    financial_year?: string;
    project_tenure?: number;
    project_area?: string;
    scheme?: string;
    dexecution_name?: string;
    execution_supervisor?: string;
    execution_post?: string;
    budgethead?: string;
    statuscode?: string;
    createdby?: string;
    createdon?: string;
    updatedby?: string;
    updatedon?: string
}